// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 2
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){












var gb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var hb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,ib=function(a){if(null==a)return String(a);var b=hb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},jb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ta=function(a){if(!a||"object"!=ib(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!jb(a,"constructor")&&!jb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||jb(a,b)},Aa=function(a,b){var c=b||("array"==ib(a)?[]:{}),d;for(d in a)if(jb(a,d)){var e=a[d];"array"==ib(e)?("array"!=ib(c[d])&&(c[d]=[]),c[d]=Aa(e,c[d])):ta(e)?(ta(c[d])||(c[d]={}),c[d]=Aa(e,c[d])):c[d]=e}return c};var Sa=null,kb=Math.random(),lb=null,la=null,ya=!1,mb={},nb={},za={};var Ba,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,V,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,
ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf;
(function(){var a=function(a){return{toString:function(){return a}}};ob=a("");pb=a("0");qb="";rb=a("");sb=a("");tb=a("");ub=a("");vb=a("");wb=a("");xb=a("");yb=a("");zb=a("2");V=a("3");Ab=a("");Bb=a("");Cb=a("");
Db=a("");Eb=a("");Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");Kb=a("");Lb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");
Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("4");Yb=a("");Zb=a("");$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");
hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("5");rc=a("");sc=a("");tc=a("6");uc=a("");vc=a("");wc=a("");xc=a("");
yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("7");Dc=a("");Ec=a("8");Fc=a("");Gc=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("9");Mc=a("");Nc=a("");
Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Ba=a("10");Zc=a("");$c=a("16");ad=a("17");bd=a("");cd=a("");
dd=a("");ed=a("");fd=a("");gd=a("");hd=a("");jd=a("");kd=a("11");ld=a("");md=a("");nd=a("");od=a("");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("12");wd=a("");xd=a("");
yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");
Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");
ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("14");ze=
a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");
Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve="";We=a("");Xe=a("");Ye=a("");Ze=a("");$e=a("");af=a("15");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=
a("");hf=a("");jf=a("");kf=a("");lf=a("")})();var bb=function(){},O=function(a){return"function"==typeof a},T=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},mf=function(a){return"number"==ib(a)&&!isNaN(a)},nf=function(a){return/^[0-9]+$/.test(a)},of=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ja=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},R=function(a){return Math.round(Number(a))||0},va=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},pf=function(a){var b=[];if(T(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},G=function(){return new Date},qa=function(a,b){if(!mf(a)||!mf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},sf=function(){this.prefix="gtm.";this.values={}};sf.prototype.set=function(a,b){this.values[this.prefix+a]=b};sf.prototype.get=function(a){return this.values[this.prefix+a]};sf.prototype.contains=function(a){return void 0!==this.get(a)};
var tf=function(a,b,c){try{if(!a[Ad])return a[Ba](a,b||bb,c||bb);c&&c()}catch(d){}return!1},uf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ja(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},vf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},wf=function(a){return function(){return a("GTM-P9FT69")}},xf=function(a){for(var b=0;b<a.length;b++)a[b]()},sa=function(){return"gtm"+yf()},
yf=function(){var a=Sa.sequence||0;Sa.sequence=a+1;return a},ua=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},zf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Af=function(a,b){0==b?a.gb=!0:a.Y=!0;var c=a.f;a.h&&(a.h.La[c]=b);mb[c]&&(mb[c].state=b)},Bf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var y=window,L=document,Df=navigator,S=function(a,b){var c=y[a];y[a]=void 0===c?b:c;return y[a]},K=function(a,b,c,d){return(d||"http:"!=y.location.protocol?a:b)+c},Ef=function(a){var b=L.getElementsByTagName("script")[0]||L.body||L.head;b.parentNode.insertBefore(a,b)},Wa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},r=function(a,b,c){var d=L.createElement("script");d.type="text/javascript";d.async=
!0;d.src=a;Wa(d,b);c&&(d.onerror=c);Ef(d);return d},ea=function(a,b){var c=L.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Ef(c);Wa(c,b);void 0!==a&&(c.src=a);return c},F=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},U=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},u=function(a){y.setTimeout(a,0)},Ya=!1,
Za=[],Ff=function(a){if(!Ya){var b=L.createEventObject,c="complete"==L.readyState,d="interactive"==L.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){Ya=!0;for(var e=0;e<Za.length;e++)u(Za[e])}Za.push=function(){for(var a=0;a<arguments.length;a++)u(arguments[a]);return 0}}},Gf=0,Hf=function(){if(!Ya&&140>Gf){Gf++;try{L.documentElement.doScroll("left"),Ff()}catch(a){y.setTimeout(Hf,50)}}},ga=function(a){var b=L.getElementById(a);if(b&&ha(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ha(document.all[a][c],
"id")==a)return document.all[a][c];return b},ha=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Ma=function(a){return a.target||a.srcElement||{}},ia=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},eb=function(a){var b=L.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},
Na=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},If=!1,Jf=[],Kf=function(){if(!If){If=!0;for(var a=0;a<Jf.length;a++)u(Jf[a])}},Lf=function(a){a=a||y;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},cb=function(a){window.console&&window.console.log&&window.console.log(a)};var oa=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||y.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||y.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:y.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=
f.split("/");0<=of(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var n=l[m].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},na=function(a){var b="";if(a&&a.href)var c=a.href.indexOf("#"),b=0>c?a.href:a.href.substr(0,c);
return b},ma=function(a){var b=L.createElement("a");a&&(b.href=a);return b};var wa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ca=function(a,b,c){F(a,b,c)},da=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=oa(ma(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},N=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},Ua=function(a,b){for(var c=
[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c};var Mf=new sf,Nf={},Pf={set:function(a,b){Aa(Of(a,b),Nf)},get:function(a){return W(a,2)},reset:function(){Mf=new sf;Nf={}}},W=function(a,b){if(2==b){var c=a.split(".");for(var f=Nf,e=0;e<c.length;e++){if(void 0===f[c[e]])return;f=f[c[e]]}return f}return Mf.get(a)},Qf=function(a,b){Mf.set(a,b);Aa(Of(a,b),Nf)},Of=function(a,b){for(var c={},d=c,e=a.split("."),
f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Rf=!1,Sf=!1;var Tf=Math.random(),Uf="0.100000">Tf;
var Vf=function(a,b){if(Uf){var c="//www.googletagmanager.com/a?id=GTM-P9FT69&cv=2",d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",G().getTime()-R(lb));c+="&sr=0.100000";d("&ps=",Tf);d("&cb=",qa());F(c)}},Wf=bb,Xf=function(){var a=!1;};var Zf=function(a){var b=Sa.zones;return b?b.checkState("GTM-P9FT69",a):Yf},Yf={active:!0,isWhitelisted:function(){return!0}};var ag=bb,bg=[],cg=!1,ra=function(a){return y["dataLayer"].push(a)},dg=function(a){var b=!1;return function(){!b&&O(a)&&u(wf(a));b=!0}},jg=function(){for(var a=!1;!cg&&0<bg.length;){cg=!0;var b=bg.shift();if(O(b))try{b.call(Pf)}catch(fb){}else if(T(b))a:{var c=b;if("string"==ib(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Nf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(fb){}}}else{var m=void 0,n=void 0,q=b;for(n in q)q.hasOwnProperty(n)&&Qf(n,q[n]);var w=!1,z=q.event;if(z){q.hasOwnProperty("gtm.uniqueEventId")||(q["gtm.uniqueEventId"]=yf(),Qf("gtm.uniqueEventId",q["gtm.uniqueEventId"]));m=q["gtm.uniqueEventId"];la=z;var t=Zf(m);if(t.active){var x=dg(q.eventCallback),D=q.eventTimeout;
D&&y.setTimeout(x,Number(D));w=ag(m,z,t.isWhitelisted,x,q.eventReporter)}}lb||(lb=q["gtm.start"])&&Wf();var A=q,C=m,J=z,H=Nf;if(!w){var B=m,I=z;}la=null;a=w||a}var M=b,P=Nf;ig();cg=!1}return!a},kg=function(){var a=jg();try{var b=y["dataLayer"].hide;if(b&&void 0!==b["GTM-P9FT69"]&&b.end){b["GTM-P9FT69"]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},lg=function(){var a=S("dataLayer",[]),b=S("google_tag_manager",{}),b=b["dataLayer"]=b["dataLayer"]||{};Za.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});
Jf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(bg.push.apply(bg,b);300<this.length;)this.shift();return jg()};bg.push.apply(bg,a.slice(0));u(kg)};var La=function(a,b,c){U(a,b,c,void 0)},ba=function(a,b,c){r(a,b,c)},Q=function(a,b){return W(a,b||2)},aa=function(a,b){y[a]=b},p=function(a,b,c){var d=y;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},v=function(a,b,c,d){return(d||"https:"==y.location.protocol?a:b)+c};var mg=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),ng={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},og={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},pg=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},qg=function(a){var b=W("gtm.whitelist");
var c=b&&pg(pf(b),ng),d=W("gtm.blacklist")||W("tagTypeBlacklist")||[];mg.test(y.location&&y.location.hostname)&&(d=pf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&pg(pf(d),og),f={};return function(g){var h=g&&g[Ba];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>of(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
of(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var q;if(!(q=0<=of(e,h.a)))a:{for(var w=h.b||[],z=new sf,t=0;t<e.length;t++)z.set(e[t],!0);for(t=0;t<w.length;t++)if(z.get(w[t])){q=!0;break a}q=!1}n=q}return f[h.a]=!k||n}};var fa=function(a){var b=L;return rg?b.querySelectorAll(a):null},sg=!1;if(L.querySelectorAll)try{var tg=L.querySelectorAll(":root");tg&&1==tg.length&&tg[0]==L.documentElement&&(sg=!0)}catch(a){}var rg=sg;var _eu=function(a){var b=String(W("gtm.elementUrl")||a[wc]||""),c=ma(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return la};_e.a="e";_e.b=["google"];var yg=/(^|\.)doubleclick\.net$/i,zg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Oa=function(a){for(var b=String(L.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=ja(e[0]);if(f&&f==a){var g=ja(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},Ag=function(a,b,c,d,e){if(yg.test(L.location.hostname)||"/"==c&&zg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=L.cookie;L.cookie=f;return g!=
L.cookie||0<=of(Oa(a),b)},Bg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Cg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Dg=function(){var a=oa(y.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var Eg=function(a,b){this.g=a;this.m=b};Eg.prototype.toString=function(){var a=""+this.g;1<this.m&&(a=a+"-"+this.m);return a};var Fg=function(a,b){this.Ja=a;this.oa=b};Fg.prototype.toString=function(){return""+this.oa+"."+this.Ja};var Ig=function(a,b){var c=new Gg(null,a,b);Hg(c);return c},Gg=function(a,b,c){this.Va=Math.floor(G().getTime()/864E5);this.na=b||"auto";this.ea=c||"/";var d=Bg(this.na),e=Cg(this.ea);this.G=a||new Eg(d,e);this.i=[];this.C=new sf},Kg=function(a,b,c){b&&(""==c.Ja?Jg(a,b):(a.C.contains(b)||a.i.push(b),a.C.set(b,c)))},Lg=function(a,b){for(var c=0;c<b.length;c++)Kg(a,b[c][0],b[c][1])},Jg=function(a,b){var c=of(a.i,b);0<=c&&a.i.splice(c,1);a.C.set(b,void 0)},Mg=function(a){for(var b=[],c=0;c<a.i.length;c++){var d=
a.i[c];b.push([d,a.C.get(d)])}return b},Ng=function(a){for(var b=0,c=0;c<a.i.length;c++)b=Math.max(b,a.C.get(a.i[c]).oa);return 864E5*b};Gg.prototype.toString=function(){if(0==this.i.length)return"";for(var a=[],b=0;b<this.i.length;b++){var c=this.i[b];a.push(""+c+"."+this.C.get(c).toString())}return"GAX1."+this.G.toString()+"."+a.join("!")};
var Og=function(a,b){for(var c=new Date,d=Cg(a.ea),e=[],f=0;f<a.i.length;f++){var g=a.i[f];a.C.get(g).oa<a.Va&&e.push(g)}for(f=0;f<e.length;f++)Jg(a,e[f]);if(a.i.length>(b||10))return!1;c.setTime(Ng(a));if("auto"!=a.na)return Ag("_gaexp",a.toString(),a.ea,a.na,c);for(var h=Dg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.G=new Eg(Bg(h[k]),d),Ag("_gaexp",a.toString(),a.ea,h[k],c)))return!0;return!1},Hg=function(a){for(var b=a.G.g,c=a.G.m,d=Oa("_gaexp"),e=[],f=0;f<d.length;f++){var g=Pg(a,d[f]);g&&e.push(g)}Bf(e,
function(a,d){var e=a.G,f=d.G;return e.g==f.g&&e.m==f.m?!1:e.g==b&&e.m==c?!0:f.g==b&&f.m==c?!1:e.g==b?f.g!=b||e.m<f.m:f.g==b?!1:e.m==c?f.g!=b&&(f.m!=c||e.g<f.g):f.m==c?!1:e.g<f.g||e.g==f.g&&e.m<f.m});a.G=0<e.length?e[0].G:new Eg(b,c);for(f=e.length-1;0<=f;f--)Lg(a,Mg(e[f]))},Pg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=ja(e[0]);if(0!=f.length){var g=2==e.length?ja(e[1]):"1";if(nf(f)&&nf(g)){d=new Eg(R(f),R(g));
break a}}}d=void 0}if(d){for(var h=new Gg(d,a.na,a.ea),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!nf(m[1]))return;Kg(h,m[0],new Fg(m[2],R(m[1])))}}return h}}};var _f=function(a){var b=String(W("gtm.referrer")||L.referrer);if(!b)return b;var c=ma(b);return b};_f.a="f";_f.b=["google"];var Tg=function(a){var b=y.location,c;(c=a[lc]?a[lc]:W("gtm.url"))&&(b=ma(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Xb]&&(f=oa(b,a[Xb],a[se],a[vc],a[fe]));return f},_u=Tg;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[zb])==String(a[V])};_eq.a="eq";_eq.b=["google"];var Ra=new String("undefined"),$a=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Ra?b:a[d]);return c.join("")}};$a.prototype.toString=function(){return this.resolve("undefined")};$a.prototype.valueOf=$a.prototype.toString;var ch={},ab=function(a,b){var c=yf();ch[c]=[a,b];return c},dh=function(a){var b=a?0:1;return function(a){var c=ch[a];if(c&&O(c[b]))c[b]();ch[a]=void 0}};var eh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},fh=function(a,b){return a<b?-1:a>b?1:0};var gh;a:{var hh=gb.navigator;if(hh){var ih=hh.userAgent;if(ih){gh=ih;break a}}gh=""}var X=function(a){return-1!=gh.indexOf(a)};var jh=function(){X("iPod")},kh=function(){return X("iPhone")&&!X("iPod")&&!X("iPad")};var lh=function(a){lh[" "](a);return a};lh[" "]=function(){};var nh=function(a,b){var c=mh;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var oh=X("Opera"),ph=X("Trident")||X("MSIE"),qh=X("Edge"),rh;if(rh=X("Gecko")){var sh=gh.toLowerCase();rh=!(-1!=sh.indexOf("webkit")&&!X("Edge"))}var th=rh&&!(X("Trident")||X("MSIE"))&&!X("Edge"),uh=gh.toLowerCase(),vh=-1!=uh.indexOf("webkit")&&!X("Edge");vh&&X("Mobile");X("Macintosh");X("Windows");X("Linux")||X("CrOS");var wh=gb.navigator||null;wh&&(wh.appVersion||"").indexOf("X11");X("Android");kh();X("iPad");jh();kh()||X("iPad")||jh();
var xh=function(){var a=gb.document;return a?a.documentMode:void 0},yh;a:{var zh="",Ah=function(){var a=gh;if(th)return/rv\:([^\);]+)(\)|;)/.exec(a);if(qh)return/Edge\/([\d\.]+)/.exec(a);if(ph)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(vh)return/WebKit\/(\S+)/.exec(a);if(oh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ah&&(zh=Ah?Ah[1]:"");if(ph){var Bh=xh();if(null!=Bh&&Bh>parseFloat(zh)){yh=String(Bh);break a}}yh=zh}
var Ch=yh,mh={},Dh=function(a){return nh(a,function(){for(var b=0,c=eh(String(Ch)).split("."),d=eh(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=fh(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||fh(0==k[2].length,0==l[2].length)||fh(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},Eh;
var Fh=gb.document;Eh=Fh&&ph?xh()||("CSS1Compat"==Fh.compatMode?parseInt(Ch,10):5):void 0;var Gh;if(!(Gh=!th&&!ph)){var Hh;if(Hh=ph)Hh=9<=Number(Eh);Gh=Hh}Gh||th&&Dh("1.9.1");ph&&Dh("9");var db=function(a,b){var c="";ph&&!Ih(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Jh)a.srcdoc=d;else if(Kh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Lh(a,d)},Jh=vh&&"srcdoc"in document.createElement("iframe"),Kh=th||vh||ph&&Dh(11),Lh=function(a,b){ph&&Dh(7)&&!Dh(10)&&6>Mh()&&Nh(b)&&(b=Oh(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};ph&&!Ih(a)?Ph(a,c):c()},Mh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Ih=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{lh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Qh=0,Ph=function(a,b){var c="goog_rendering_callback"+Qh++;gb[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Nh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Oh=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var fi=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=ci(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=di(f,g);ei(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},gi=null,ci=function(a){if(gi)return gi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return gi=
c}0==a.styleSheets.length&&a.createStyleSheet();return gi=a.styleSheets[0]},di=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},ei=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var ni={},oi=void 0,pi=function(a){var b=ni[a];b||(b={id:a,v:[],ba:0,Na:null,Ca:void 0,Ga:!1},ni[a]=b);oi=b},ri=function(a,b,c,d){var e=oi;if(!rg||!e)return!1;var f={id:e.id+":"+e.v.length,ob:b,X:[],jb:c,H:a,ya:0,wa:d||null,Ua:0,aa:!1};e.v.push(f);null===a?(f.aa=!0,b(null)):qi(e);return!0},si=function(a){var b=fi(a,"visibility","hidden",!0);return function(){O(b)&&b.apply();b=null}},ti=function(a,b,c,d){var e=b;if(!Ya){var f=si(a.A);Za.push(f);e=function(a,c){var d=b(a,c);f();return d}}return ri(a,
e,c,d)},qi=function(a){if(!a.Ga){for(var b=a.ba;b<a.v.length;b++){var c=a.v[b],d=b==a.ba;if(!c.aa&&!ui(d,c))break;c.aa&&d&&a.ba++}a.v.length>a.ba?(a.Na||(a.Na=y.setTimeout(function(){a.Na=null;qi(a)},80)),Ya||a.Ca||(a.Ca=function(){u(function(){qi(a)})},U(L,"DOMContentLoaded",a.Ca))):vi(a)}},vi=function(a){for(var b=0;b<a.v.length;b++){var c=a.v[b];if(c.H)for(var d=fa(c.H.A)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(wi(f,c.id),c.X.push(xi(f,c.id)))}}},
ui=function(a,b){var c=[];if(b.H){var d=yi(b.H,b.id),e=null;b.wa&&(e=yi(b.wa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!Ya&&(null===b.wa.s||b.Ua+c.length<b.wa.s)))break;c.push({element:g,ac:h})}}if(!Ya&&b.jb&&(!a||null==b.H.s||b.H.s!=b.ya+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].ac,n;b.ya++;wi(l,b.id);m&&(b.Ua++,n=b.id+"-t",wi(m,n));var q=b.ob(l,m);O(q)&&b.X.push(q);b.X.push(xi(l,b.id));m&&n&&b.X.push(xi(m,n))}if(b.H.s&&
b.H.s==b.ya||Ya)b.aa=!0;return!0},wi=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},xi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},yi=function(a,b){for(var c=fa(a.A)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.F&&!zi(f))break;d.push(f)}}return d},zi=function(a){if(Ya)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Da,Ai,Bi,Ja=/(Firefox\D28\D)/g.test(Df.userAgent),Di=function(a,b){return function(c){c=c||y.event;var d=Ma(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Na(d,["a","area"]),e=!d||!d.href||Ci(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Da:Bi;if(c.defaultPrevented||!1===c.returnValue||c.ca&&c.ca()){if(d){var g={simulateDefault:!1},h=Ea(f,["wnc","nwnc"]);h&&Fa(a,d,g,f.wt,h)}}else{if(d){var g={},k,l=Ea(f,
["wnc","nwnc","nwc","wc"]);(k=Fa(a,d,g,f.wt,l))||(Ga(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&Ja;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=Ka(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},Fa=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||ha(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=Ei(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=Fi(b);g.eventTimeout=f;g.eventCallback=Gi(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return ra(g)},
Fi=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},Ia=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Ka=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Df.userAgent),e=Ia(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=y.frames&&y.frames[f]||y[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+G().getTime(),b.targetWindow=y.open("",b.targetWindowName));break;default:d&&!y.frames[e]?(b.simulateDefault=!1,c=!0):(y.frames[e]||(b.targetWindowName=e),b.targetWindow=y.frames[e]||y.open("",e))}return c},Ei=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||G().getTime(),500>G().getTime()-c&&y.setTimeout(Ei(a,b,c),25)))}},Gi=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);L.gtmSubmitFormNow=!0;Ha(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||G().getTime(),500>G().getTime()-c&&y.setTimeout(Gi(a,b,c),25)}},Ea=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Hi=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},Ga=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<Ii.length;c++)if(a.passingRules[c]){var d=Ji[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Ii[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},pa=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(L.gtmHasClickListenerTag)return;L.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Ma(a);b&&Fa("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Ai&&(Ai=na(L.location));Hi(Bi,b||!1,c||!1,d,e);if(L.gtmHasLinkClickListenerTag)return;
L.gtmHasLinkClickListenerTag=!0;f="click";g=Di(a,b||!1);break;case "FORM_SUBMIT":Hi(Da,b||!1,c||!1,d,e);if(L.gtmHasFormSubmitListenerTag)return;L.gtmHasFormSubmitListenerTag=!0;f="submit";g=Di(a,b||!1);break;default:return}U(L,f,g,h)},Ci=function(a){if(!Ai)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ma(a);return Ai==na(c)},Ha=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
L.gtmFormElementSubmitter||(L.gtmFormElementSubmitter=L.createElement("form"));return L.gtmFormElementSubmitter.submit.call?L.gtmFormElementSubmitter.submit:a.submit},Ki=function(){var a=function(a){var b=S("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Bi=a("linkClickMap");Da=a("formSubmitMap")};var xa=function(a,b){var c=b||gb,d=c.onerror,e=!1;vh&&!Dh("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,ab:h,sc:k,error:l});return e}};var ej=function(a){if(!a)return!1;if(a[yb]&&T(a[V])){for(var b=a[V],c=0;c<b.length;c++)if(a[V]=b[c],tf(a))return!0;return!1}return tf(a)};var zj=26,Aj=[],Bj=[],Cj=[],Dj=new sf,Ej=[],Z=[],Ii=[],Ji=[],Fj=function(){this.N=[]};Fj.prototype.set=function(a,b){this.N.push([a,b]);return this};Fj.prototype.resolve=function(a,b){for(var c={},d=0;d<this.N.length;d++){var e=Gj(this.N[d][0],a,b),f=Gj(this.N[d][1],a,b);c[e]=f}return c};var Hj=function(a){this.index=a};Hj.prototype.resolve=function(a,b){var c=Cj[this.index];if(c&&!b(c)){var d=c[kd];if(a){if(a.get(d))return;a.set(d,!0)}c=Gj(c,a,b);a&&a.set(d,!1);return tf(c)}};
var _M=function(a){return new Hj(a)},Ij=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Gj(Aj[a[f]],b,c);g===Ra&&(e=!0);d.push(g)}return e?new $a(d):d.join("")}},_T=function(a){return new Ij(arguments)},Jj=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Gj(a[0],c,d);if(a[0]instanceof Hj&&b(8)&&b(16)){if(e===Ra)return e;var f=sa();Dj.set(f,e);return'google_tag_manager["GTM-P9FT69"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new Jj(arguments)},Kj=function(a,b){this.w=a;this.va=b},_R=function(a,b){return new Kj(a,b)};
var Gj=function(a,b,c){var d=a;if(a instanceof Hj||a instanceof Fj||a instanceof Ij||a instanceof Jj)return a.resolve(b,c);if(!(a instanceof Kj))if(T(a))for(var d=[],e=0;e<a.length;e++)d[e]=Gj(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Gj(a[f],b,c))}return d},Nj=function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','2455843_2147479553',_ua,true,'UA-1217838-28',false,'\x26tid',{10:8},1,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=
Mj(c,a);return b},Mj=function(a,b){var c=b[a],d=c;if(c instanceof Hj||c instanceof Jj||c instanceof Ij||c instanceof Kj)d=c;else if(T(c))for(var d=[],e=0;e<c.length;e++)d[e]=Mj(c[e],b);else if("object"==typeof c){var d=new Fj,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Mj(c[f],b))}return d},Pj=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
Aj[e[1]]);if(1==a)for(var f=Oj(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Bj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Oj(e[g]);3==a&&(c[d]=Aj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Aj[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Oj=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<zj;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);
2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Qj=function(a,b,c){a.push.apply(a,Pj(b,c))};
var fg=function(){},Yj=function(a){},ig=function(){},Zj=function(a){},ak=function(a,b){},bk=function(a,b){},gg=function(a){};var ck,dk;
var pk=function(a){return function(){}},qk=function(a){return function(){}};var rk=function(a){var b=this;this.f=a;this.Y=this.gb=!1;this.ua=[];this.pa=[];this.V=function(){if(b.h&&b.h.event){var c=b.h.event,d=b.f;}b.Y||xf(b.ua);Af(b,1);if(nb[a])for(var e=0;e<nb[a].length;e++)nb[a].shift().V()};this.U=function(){if(b.h&&b.h.event){var c=b.h.event,d=b.f;}b.Y||xf(b.pa);
Af(b,2);if(nb[a])for(var e=0;e<nb[a].length;e++)nb[a].shift().U()};this.B=bb},sk=function(a,b){a.ua.push(b)},tk=function(a,b){a.pa.push(b)},uk=function(a){this.J=[];this.Ka=[];this.Wa={};this.bb=[];this.T=0;this.Ia={};this.Ma={};this.La={};this.event=a};uk.prototype.addListener=function(a){this.bb.push(a)};
var vk=function(a){0<a.T||xf(a.bb)},wk=function(a,b,c,d,e,f){if(!c.Y){a.J[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=T(d)?d.slice():["or",d];e=T(e)?e.slice():[e];f=T(f)?f.slice():[f];a.Wa[b]=d;a.Ia[b]=0<e.length;a.Ma[b]=0<f.length;a.T++;var g=function(){0<a.T&&!a.Ia[b]&&!a.Ma[b]&&a.T--;vk(a)};sk(c,g);tk(c,g)}},Bk=function(a){for(var b=[],c={},d=0;d<a.J.length;c={O:c.O},d++)if(c.O=a.J[d],c.O){var e=a.Wa[d],f=a.Ia[d],g=a.Ma[d];if(0!=e.length||f||g){if(0<e.length)for(var h=xk(e,c.O.B),
k=0;k<e.length;k++)e[k]instanceof Kj&&e[k].w!=d&&yk(a,e[k].w,h);(f||g)&&zk(a,d,function(a){return function(){0<a.O.h.T&&a.O.h.T--;vk(a.O.h)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.J[b[d]].B();for(d=0;d<a.Ka.length;d++){var l=a.Ka[d];Ak(l);0<l.length&&l[0].B()}},yk=function(a,b,c){a.J[b]&&(sk(a.J[b],function(){c(b,!0)}),tk(a.J[b],function(){c(b,!1)}))},xk=function(a,b){var c=bb,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof Kj&&a[h].w===e||a[h]===e){g=h;break a}g=
-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},zk=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=Z[b];if(a.event.c(h)){}else g=Ck(h,b,a.event.c,a);if(c=g){var k=Dk(b,!0);0<k.length&&f(k[0].w);d.push(c);var l=Dk(b,!1);0<l.length&&f(l[0].w)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=Dk(h.f,!0);if(0<k.length){var l=d[g-1],m=Ek(h);sk(l,m);0==k[0].va?tk(l,m):tk(l,c)}var n=Dk(h.f,!1);0<n.length&&(m=Ek(d[g+1]),sk(h,m),0==n[0].va?tk(h,m):tk(h,c))}sk(d[d.length-1],c);tk(d[d.length-1],c);a.Ka.push(d)}},Dk=function(a,b){var c=b?pe:Ge,d=Z[a],e=void 0===d[c]?[]:d[c];return T(e)?e:[e]},Ek=function(a){return function(){a.B()}},Ak=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.f,f=mb[e],g=f.firingOption;0!=g&&(1==g&&void 0!==
d.h.La[e]||2==g&&void 0!==f.state)&&b.push(d)}var h=Fk(b),k;for(k in h)if(h.hasOwnProperty(k)){for(var l=void 0,m=void 0,n=h[k],q=n[0],w=n[n.length-1],z,t=0;t<a.length;t++){var x=a[t];!l&&x.f==q&&0<t&&(l=a[t-1]);x.f==w&&t<a.length-1&&(m=a[t+1]);if(-1<of(n,x.f))if(z=a.splice(t,1)[0],x.f==w)break;else t--}if(z){var D=Number(k),A=l,C=m;if(A){var J=A.ua[0],H=A.pa[0],E=A;E.ua=[];E.pa=[];sk(A,J);tk(A,H)}if(A&&C){var B=Ek(C);sk(A,B);var I=Dk(A.f,!1);0<I.length&&I[0].w!=D&&0==I[0].va&&tk(A,B);var M=Dk(C.f,
!0);0<M.length&&M[0].w!=D&&0==M[0].va&&tk(A,B)}}}},Fk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Dk(a,!0);0<b.length&&f(b[0].w);e.push(a);var c=Dk(a,!1);0<c.length&&f(c[0].w)};f(d.f);b[d.f]=e}Gk(a,b);return b},Gk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].f,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<of(b[e],d)){delete b[d];break}}};var Ik=function(a,b,c){return function(){a[$c]=b.V;a[ad]=b.U;var d=b.f,e=b.h&&b.h.La[d],f=mb[d]&&mb[d].state,g=e?void 0!==e:b.gb||b.Y,h=mb[d]&&mb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){Af(b,0);var m=b.h?b.h.event:void 0;a=Hk(a,c);if(m){var n=a;ak(m,d)}tf(a,b.V,b.U)}else k&&0==f||l&&0==e?nb[d].push(b):k&&1==f||l&&1==e?b.V():b.U()}},Hk=function(a,b){a=Gj(a,new sf,b);return a},Ck=function(a,b,c,d){var e=d&&d.J,f;if(f=e)a:{if(e&&T(e)&&0!=e.length)for(var g=0;g<e.length;g++)if(e[g]&&e[g].f===b){f=e[g];break a}f=void 0}var h=f||new rk(b);h.h=d;sk(h,pk(a));tk(h,qk(a));h.B=Ik(a,h,c);return h};
var Nk=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];y[l()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!ta(b))return!1;for(var e=ua(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;if(a[Ec]){c=W("ecommerce");
}else a[Dc]&&(c=a[Dc].ecommerce);if(!ta(c))return;c=Object(c);var e=ua(a[Wc],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=
c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&z[e]||!c&&void 0===z[e])){var f=t[e]?va(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}S("GoogleAnalyticsObject",a[Gd]||"ga");var l=function(){return y.GoogleAnalyticsObject},m=S(l(),function(){var a=y[l()];a.q=a.q||[];a.q.push(arguments)});m.l=Number(G());
var n="",q="";"string"!=typeof a[Te]?(q=sa(),n=q+"."):""!==a[Te]&&(q=a[Te],n=q+".");var w=!1;var x={name:q};m("create",a[pb],x);d("set","&gtm","GTM-P9FT69");var A;a[vd]&&d("require","linkid","linkid.js");
d("set","hitCallback",function(){if(O(a[bd]))a[bd]();else{var c=a[Wc],d=c&&c.hitCallback;O(d)&&d()}b()});if(a[Pe]){}else if(a[Qe]){}else if(a[Se]){}else if(a[Re]){}else if(a[uc]){}else if(a[sc]){}else if(a[Oe]){}else{a[Lc]&&(d("require","ec","ec.js"),h());if(a[Cc]&&!a[Nc]){var P="_dc_gtm_"+String(a[pb]).replace(/[^A-Za-z0-9-]/g,
"");d("require","displayfeatures",void 0,{cookieName:P})}A?d("send","pageview",A):d("send","pageview");}if(!Nk){var ka=a[qc]?"u/analytics_debug.js":"analytics.js";a[ld]&&!a[qc]&&(ka="internal/"+ka);Nk=!0;r(K("https:","http:","//www.google-analytics.com/"+ka,w),function(){y[l()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var Ok=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Ej[b]&&Gj(Ej[b],new sf,c),e=d;d&&(e=ej(d));a[b]=[e,d]}return a[b]}},Xj=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.S(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.S(e[d],a.c)[0])return!1;return!0},Pk=function(a){for(var b=new uk(a),c=0;c<zj;c++)if(a.ka[c]&&!a.ta[c])if(a.c(Z[c])){}else{var d=a.W[c],e=Ck(d,c,a.c,b);wk(b,c,e,d[xc],d[pe],d[Ge]);if(d[ob])break}b.addListener(a.la);Bk(b);vk(b)},Qk=!1,ag=function(a,b,c,d,e){switch(b){case "gtm.js":if(Qk)return!1;Qk=!0;break;case "gtm.sync":if(W("gtm.snippet")!=kb)return!1}for(var f={id:a,name:b,la:d||bb,ka:Oj(),ta:Oj(),S:Ok(),c:qg(c)},g=[],h=0;h<Ii.length;h++)if(Xj(f,Ii[h])){g[h]=!0;for(var k=
f,l=Ii[h],m=l[1],n=0;n<m.length;n++)k.ka[m[n]]=!0;for(var q=l[3],n=0;n<q.length;n++)k.ta[q[n]]=!0}else g[h]=!1;ak(f);var z=[];for(var t=0;t<zj;t++)if(f.ka[t]&&!f.ta[t])if(f.c(Z[t])){}else{z[t]=Z[t];}f.W=z;Pk(f);e&&O(e)&&e({passingRules:g,resolvedTags:f.W});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var H in f.W)if(f.W.hasOwnProperty(H)){var E=f.W[H],B;if(!(B=void 0==E[kd])){var I=E[kd];B=!("function"!=typeof String.prototype.startsWith?0===I.indexOf("_implicit"):I.startsWith("_implicit"))}if(B)return!0}return!1};var Sk=function(){};var Tk=function(){};var Rk={macro:function(a){if(Dj.contains(a))return Dj.get(a)}};Rk.dataLayer=Pf;Rk.onHtmlSuccess=dh(!0);Rk.onHtmlFailure=dh(!1);Rk.callback=function(a){za.hasOwnProperty(a)&&O(za[a])&&za[a]();delete za[a]};
Rk.vb=function(){var a=y.google_tag_manager;a||(a=y.google_tag_manager={});Sa=a;if(a["GTM-P9FT69"]){var b=Sa.zones;b&&b.registerNatural("GTM-P9FT69")}else{a["GTM-P9FT69"]=Rk;Ki();Aj.push.apply(Aj,Nj());Qj(Bj,0,"10:0,10:1,11:2,2:3,3:4,10:6,13:7,0:8,9:7,8:7,15:7,5:9,6:7,1:11,12:9,7:9,14:12,10:13,11:14,11:15,4:16,11:17,4:18,10:19,11:20,11:21");Qj(Cj,1,"G,AAgB,AAgG,AAgY,AAAgB,CAAAC");Qj(Ej,1,"Z");Qj(Z,1,"g_f");Qj(Ii,2,"B:B::");Qj(Ji,4,"5:");for(var c=0;c<Z.length;c++){var d=Z[c],
e=1;d[Nd]?e=2:d[Ye]&&(e=0);mb[c]={firingOption:e,state:void 0};nb[c]=[]}Xf();lg();var q=y;if("interactive"==L.readyState&&!L.createEventObject||"complete"==L.readyState)Ff();else{U(L,"DOMContentLoaded",Ff);U(L,"readystatechange",Ff);if(L.createEventObject&&L.documentElement.doScroll){var w=!0;try{w=!q.frameElement}catch(z){}w&&Hf()}U(q,
"load",Ff)}"complete"===L.readyState?Kf():U(y,"load",Kf);Tk();Sk()}};Rk.vb();var _vs="res_ts:1476787892530000,srv_cl:151358218,ds:live,cv:2";
})()
